[package]
name = "pokeball-rs"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = {version = "1.3.0", optional = true}

[features]
default = []
full = ["uuid"]
uuid = ["dep:uuid"]
